---
services:
  nifi-toolkit:
    image: apache/nifi-toolkit:1.28.1
    container_name: nifi-toolkit
    entrypoint: /bin/bash
    command: /tmp/tls-scripts/nifi-gen-certs.sh
    volumes:
      - tls-cert:/tmp/tls-certs
      - tls-scripts:/tmp/tls-scripts
    environment:
      - KEYSTORE_PASSWORD_NIFI=${KEYSTORE_PASSWORD_NIFI}
      - KEYSTORE_PASSWORD_NIFI_REG=${KEYSTORE_PASSWORD_NIFI_REG}
      - TRUSTSTORE_PASSWORD=${TRUSTSTORE_PASSWORD}
  nifi:
    image: local-nifi:test
    depends_on:
      nifi-toolkit:
        condition: service_completed_successfully
      keycloak:
        condition: service_started
      postgresql:
        condition: service_started
    volumes:
      - nifi-conf:/opt/nifi/nifi-current/persistent_conf
      - tls-cert-nifi:/tmp/tls-certs
    ports:
      - 127.0.0.1:8080:8080
    environment:
      - NAMESPACE=local
      - CONSUL_ENABLED=true
      - CONSUL_URL=consul:8500
      - AUTH=oidc
      - NIFI_NEW_SENSITIVE_KEY=${NIFI_SENSITIVE_KEY}
      - NIFI_WEB_HTTPS_PORT=8080
      - KEYSTORE_PATH=/tmp/tls-certs/keystore.p12
      - KEYSTORE_TYPE=PKCS12
      - KEYSTORE_PASSWORD=${KEYSTORE_PASSWORD_NIFI}
      - TRUSTSTORE_PATH=/tmp/tls-certs/truststore.p12
      - TRUSTSTORE_TYPE=PKCS12
      - TRUSTSTORE_PASSWORD=${TRUSTSTORE_PASSWORD}
      - INITIAL_ADMIN_IDENTITY=CN=admin, OU=NIFI
      - OIDC_CLIENT_ID=frontend
      - OIDC_CLIENT_SECRET=frontend
      - "OIDC_DISCOVERY_URL_NEW=http://keycloak:8080/realms/nifi-test-realm/.well-known/openid-configuration"
    container_name: local-nifi-oidc
    restart: unless-stopped
  nifi-registry:
    image: ghcr.io/netcracker/nifi-registry:latest
    depends_on:
      nifi-toolkit:
        condition: service_completed_successfully
      keycloak:
        condition: service_started
      postgresql:
        condition: service_started
    volumes:
      - tls-cert-reg:/tmp/tls-certs
    ports:
      - 127.0.0.1:18080:18080
    environment:
      - AUTH=oidc
      - NIFI_REGISTRY_WEB_HTTPS_PORT=18080
      - NIFI_REGISTRY_WEB_HTTP_HOST=0.0.0.0
      - KEYSTORE_PATH=/tmp/tls-certs/keystore.p12
      - KEYSTORE_TYPE=PKCS12
      - KEYSTORE_PASSWORD=${KEYSTORE_PASSWORD_NIFI_REG}
      - TRUSTSTORE_PATH=/tmp/tls-certs/truststore.p12
      - TRUSTSTORE_TYPE=PKCS12
      - TRUSTSTORE_PASSWORD=${TRUSTSTORE_PASSWORD}
      - INITIAL_ADMIN_IDENTITY=CN=admin, OU=NIFI
      - OIDC_CLIENT_ID=frontend
      - OIDC_CLIENT_SECRET=frontend
      - "OIDC_DISCOVERY_URL_NEW=http://keycloak:8080/realms/nifi-test-realm/.well-known/openid-configuration"
    container_name: local-nifi-registry-oidc
    hostname: nifi-registry
    restart: unless-stopped
  consul:
    image: hashicorp/consul:1.20
    ports:
      - 127.0.0.1:8500:8500
    hostname: consul
  keycloak:
    image: keycloak/keycloak:26.1.4
    hostname: keycloak
    restart: on-failure:3
    depends_on:
      postgresql:
        condition: service_started
    volumes:
      - keycloak-init:/opt/keycloak/data/import
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgresql:5432/postgres
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - 28080:8080
    command:
      - start-dev
      - "--import-realm"
      - "--hostname"
      - "http://localhost:28080"
      - "--hostname-backchannel-dynamic"
      - "true"
  postgresql:
    image: postgres:16.8
    ports:
      - "5430:5432"
    volumes:
      - pg-db:/var/lib/postgresql/data/pgdata
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
    container_name: postgresql
    hostname: postgresql
volumes:
  tls-scripts:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: $BASE_DIR/.github/workflows/sh/
  tls-cert:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: $BASE_DIR/temp-vol/tls-cert/
  tls-cert-nifi:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: $BASE_DIR/temp-vol/tls-cert/nifi/
  tls-cert-reg:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: $BASE_DIR/temp-vol/tls-cert/nifi-registry/
  nifi-conf:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: $BASE_DIR/temp-vol/nifi/per-conf/
  pg-db:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: $BASE_DIR/temp-vol/pg-db
  keycloak-init:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: $BASE_DIR/.github/configuration/keycloak/