---
services:
  nifi-toolkit:
    image: apache/nifi-toolkit:1.28.1
    depends_on:
      consul:
        condition: service_started
    container_name: nifi-toolkit
    entrypoint: /bin/bash
    command: /tmp/tls-scripts/nifi-gen-certs.sh
    volumes:
      - tls-cert:/tmp/tls-certs
      - tls-scripts:/tmp/tls-scripts
    environment:
      - KEYSTORE_PASSWORD_NIFI=${KEYSTORE_PASSWORD_NIFI}
      - KEYSTORE_PASSWORD_NIFI_REG=${KEYSTORE_PASSWORD_NIFI_REG}
      - TRUSTSTORE_PASSWORD=${TRUSTSTORE_PASSWORD}
      - CONSUL_ACL_ENABLED=true
      - CONSUL_HOSTNAME=consul
      - CONSUL_TOKEN=${CONSUL_TOKEN}
      - CONSUL_READ_TOKEN=${CONSUL_READ_TOKEN}
  nifi:
    image: local-nifi:test
    depends_on:
      nifi-toolkit:
        condition: service_completed_successfully
    volumes:
      - nifi-conf:/opt/nifi/nifi-current/persistent_conf
      - tls-cert-nifi:/tmp/tls-certs
    ports:
      - 127.0.0.1:8080:8080
    environment:
      - NAMESPACE=local
      - CONSUL_ENABLED=true
      - CONSUL_URL=consul:8500
      - AUTH=tls
      - NIFI_NEW_SENSITIVE_KEY=${NIFI_SENSITIVE_KEY}
      - NIFI_WEB_HTTPS_PORT=8080
      - KEYSTORE_PATH=/tmp/tls-certs/keystore.p12
      - KEYSTORE_TYPE=PKCS12
      - KEYSTORE_PASSWORD=${KEYSTORE_PASSWORD_NIFI}
      - TRUSTSTORE_PATH=/tmp/tls-certs/truststore.p12
      - TRUSTSTORE_TYPE=PKCS12
      - TRUSTSTORE_PASSWORD=${TRUSTSTORE_PASSWORD}
      - INITIAL_ADMIN_IDENTITY=CN=admin, OU=NIFI
      - CONSUL_ACL_TOKEN=${CONSUL_TOKEN}
    container_name: local-nifi
    restart: unless-stopped
  nifi-registry:
    image: ghcr.io/netcracker/qubership-nifi-registry:latest
    depends_on:
      nifi-toolkit:
        condition: service_completed_successfully
    volumes:
      - tls-cert-reg:/tmp/tls-certs
    ports:
      - 127.0.0.1:18080:18080
    environment:
      - AUTH=tls
      - NIFI_REGISTRY_WEB_HTTPS_PORT=18080
      - NIFI_REGISTRY_WEB_HTTP_HOST=0.0.0.0
      - KEYSTORE_PATH=/tmp/tls-certs/keystore.p12
      - KEYSTORE_TYPE=PKCS12
      - KEYSTORE_PASSWORD=${KEYSTORE_PASSWORD_NIFI_REG}
      - TRUSTSTORE_PATH=/tmp/tls-certs/truststore.p12
      - TRUSTSTORE_TYPE=PKCS12
      - TRUSTSTORE_PASSWORD=${TRUSTSTORE_PASSWORD}
      - INITIAL_ADMIN_IDENTITY=CN=admin, OU=NIFI
    container_name: local-nifi-registry
    hostname: nifi-registry
  consul:
    image: hashicorp/consul:1.20
    volumes:
      - consul-conf:/consul/config
    ports:
      - 127.0.0.1:8500:8500
    hostname: consul
volumes:
  tls-scripts:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${GIT_BASE_DIR:-$BASE_DIR}/.github/workflows/sh/
  tls-cert:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: $BASE_DIR/temp-vol/tls-cert/
  tls-cert-nifi:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: $BASE_DIR/temp-vol/tls-cert/nifi/
  tls-cert-reg:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: $BASE_DIR/temp-vol/tls-cert/nifi-registry/
  nifi-conf:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: $BASE_DIR/temp-vol/nifi/per-conf/
  consul-conf:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${GIT_BASE_DIR:-$BASE_DIR}/.github/configuration/consul/
