---
name: maven-build-and-test

on:
  push:
    paths:
      - '.github/workflows/maven-build-and-test.yml'
      - 'qubership-bundle/**'
      - 'qubership-consul/**'
      - 'qubership-nifi-bulk-redis-service/**'
      - 'qubership-nifi-bundle-common/**'
      - 'qubership-nifi-common/**'
      - 'qubership-nifi-db-bundle/**'
      - 'qubership-nifi-lookup-services/**'
      - 'qubership-services/**'
      - 'pom.xml'
  pull_request:
    paths:
      - '.github/workflows/maven-build-and-test.yml'
      - 'qubership-bundle/**'
      - 'qubership-consul/**'
      - 'qubership-nifi-bulk-redis-service/**'
      - 'qubership-nifi-bundle-common/**'
      - 'qubership-nifi-common/**'
      - 'qubership-nifi-db-bundle/**'
      - 'qubership-nifi-lookup-services/**'
      - 'qubership-services/**'
      - 'pom.xml'
  workflow_dispatch:
    inputs:
      java-version:
        required: false
        type: string
        default: "21"
        description: 'Java version (e.g., 21)'
      upload-artifact:
        required: false
        type: boolean
        default: false
        description: 'If set, uploads build results to action run'
      artifact-id:
        default: artifact
        required: false
        type: string
        description: 'Artifact name to use for artifact upload'
      skip-sonar:
        default: false
        required: false
        type: boolean
        description: 'If set, skips sonar cloud analysis'
  workflow_call:
    inputs:
      java-version:
        required: false
        type: string
        default: "21"
      upload-artifact:
        required: false
        type: boolean
        default: false
      artifact-id:
        default: artifact
        required: false
        type: string
      skip-sonar:
        default: false
        required: false
        type: boolean

permissions:
  contents: read

jobs:
  maven-build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Input parameters
        run: |
          echo "Java version: ${JAVA_VERSION}" >> $GITHUB_STEP_SUMMARY
        env:
          JAVA_VERSION: "${{ github.event.inputs.java-version || '21' }}"
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0
          persist-credentials: false
      - name: Cache Maven dependencies
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK
        uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5.0.0
        with:
          java-version: ${{ inputs.java-version || '21' }}
          distribution: 'temurin'
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.gpg-private-key }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
      - name: Run local maven build with sonar
        if: ${{ !inputs.skip-sonar }}
        run: >
          mvn --batch-mode package
          -Dgpg.skip=true
          org.sonarsource.scanner.maven:sonar-maven-plugin:${SONAR_PLUGIN_VERSION}:sonar
          -Dsonar.projectKey=${SONAR_PROJECT_KEY} -Dsonar.organization=${SONAR_ORGANIZATION}
          -Dsonar.host.url=${SONAR_HOST_URL}
        env:
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_PLUGIN_VERSION: "${{ vars.SONAR_PLUGIN_VERSION }}"
          SONAR_ORGANIZATION: "${{ vars.SONAR_ORGANIZATION }}"
          SONAR_PROJECT_KEY: "${{ vars.SONAR_PROJECT_KEY }}"
          SONAR_HOST_URL: "${{ vars.SONAR_HOST_URL }}"
      - name: Run local maven build w/o sonar
        if: ${{ inputs.skip-sonar }}
        run: >
          mvn --batch-mode package
        env:
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Upload test results
        if: failure() || cancelled()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: maven-unit-test-logs
          path: |
            **/target/surefire-reports/**/*.xml
          retention-days: 2
      - name: Upload all Maven target directories
        if: ${{ inputs.upload-artifact }}
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: ${{ inputs.artifact-id }}
          path: '**/target'
          retention-days: 1
